<?php

namespace Test\FilmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QualityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualityRepository extends EntityRepository
{
}
